/**
 * Copyright 2026 Google LLC
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 * Cleans up unused PHP registration templates generated by @wordpress/build.
 *
 * @wordpress/build automatically generates runtime registration files
 * (build.php, modules.php, scripts.php, etc.) meant for Gutenberg.
 * These files lack direct file access guards (ABSPATH check), call
 * wp_deregister_script_module() which requires WP 6.5+, and declare
 * unprefixed global variables.
 *
 * This plugin registers and enqueues its assets directly from build/scripts/
 * via its own PHP classes and does not use script modules, so these generated
 * runtime PHP files are neither needed nor shipped.
 */

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname( fileURLToPath( import.meta.url ) );
const buildDir = path.resolve( __dirname, '../../build' );

if ( fs.existsSync( buildDir ) ) {
	const filesToRemove = [
		'build.php',
		'modules.php',
		'scripts.php',
		'styles.php',
		'constants.php',
		'routes.php',
		'widgets.php',
		'pages.php',
		'scripts/registry.php',
	];

	for ( const file of filesToRemove ) {
		const filePath = path.join( buildDir, file );
		if ( fs.existsSync( filePath ) ) {
			fs.rmSync( filePath, { force: true } );
		}
	}

	const dirsToRemove = [
		'modules',
		'styles',
		'routes',
		'widgets',
		'pages',
	];

	for ( const dir of dirsToRemove ) {
		const dirPath = path.join( buildDir, dir );
		if ( fs.existsSync( dirPath ) ) {
			fs.rmSync( dirPath, { recursive: true, force: true } );
		}
	}
}
